const Nombre = document.getElementById("name")
const ID = document.getElementById("name")
const Apellido = document.getElementById("name")
const email = document.getElementById("email")
const password = document.getElementById("password")
const form = document.getElementById("form")
const parrafo = document.getElementById("warnings")
